### ISSUE TITLE
PSL?

### ISSUE THREAD

**Issue by StevenLOL** [YingyuLiang/SIF#1]
Hi, thanks for sharing the code. 

Would you please point out which part of the code is refer to the "PSL" in your paper ? I only manage to found two weighting functions:

```
def getWeight(words, word2weight):
...
def getIDFWeight(wordfile, save_file=''):
```

**Comment by YingyuLiang** [comment]
PSL refers to the word vector file paragram_sl999_small.txt.  You can 
1. download it from John Wieting's github (https://github.com/jwieting/iclr2016)
2. replace the file glove.840B.300d.txt in the scripts in the examples folder (sif_embedding.py, sim_sif.py, sim_tfidf.py,  supervised_sif_proj.sh) with paragram_sl999_small.txt
3. run demo.sh

**Comment by StevenLOL** [comment]
Cool!
